name: Windows Installer

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Install Inno Setup
        run: choco install innosetup -y
      - name: Build + Publish + Create Installer
        shell: pwsh
        run: |
          cd ScaffGuard
          ./build.ps1
      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: ScaffGuard-Setup
          path: ScaffGuard/Installer/Output/ScaffGuard-Setup.exe
